<?php

namespace RegistroVehiculosBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConductoresRepository extends \Doctrine\ORM\EntityRepository
{
}
