<?php

namespace RegistroVehiculosBundle\Repository;

/**
 * SecretariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretariaRepository extends \Doctrine\ORM\EntityRepository
{
}
