conductores_index:
    path:     /
    defaults: { _controller: "RegistroVehiculosBundle:Conductores:index" }
    methods:  GET

conductores_show:
    path:     /{id}/show
    defaults: { _controller: "RegistroVehiculosBundle:Conductores:show" }
    methods:  GET

conductores_new:
    path:     /new
    defaults: { _controller: "RegistroVehiculosBundle:Conductores:new" }
    methods:  [GET, POST]

conductores_edit:
    path:     /{id}/edit
    defaults: { _controller: "RegistroVehiculosBundle:Conductores:edit" }
    methods:  [GET, POST]

conductores_delete:
    path:     /{id}/delete
    defaults: { _controller: "RegistroVehiculosBundle:Conductores:delete" }
    methods:  DELETE
