secretaria_index:
    path:     /
    defaults: { _controller: "RegistroVehiculosBundle:Secretaria:index" }
    methods:  GET

secretaria_show:
    path:     /{id}/show
    defaults: { _controller: "RegistroVehiculosBundle:Secretaria:show" }
    methods:  GET

secretaria_new:
    path:     /new
    defaults: { _controller: "RegistroVehiculosBundle:Secretaria:new" }
    methods:  [GET, POST]

secretaria_edit:
    path:     /{id}/edit
    defaults: { _controller: "RegistroVehiculosBundle:Secretaria:edit" }
    methods:  [GET, POST]

secretaria_delete:
    path:     /{id}/delete
    defaults: { _controller: "RegistroVehiculosBundle:Secretaria:delete" }
    methods:  DELETE
